object dtmConexao: TdtmConexao
  OnCreate = DataModuleCreate
  Height = 491
  Width = 1050
  PixelsPerInch = 120
  object ConexaoDB: TFDConnection
    Params.Strings = (
      'Database=C:\Git\delphi-course-projects\BANCO.FDB'
      'User_Name=SYSDBA'
      'Password=masterkey'
      'DriverID=FB')
    Connected = True
    LoginPrompt = False
    Left = 88
    Top = 40
  end
  object FDPhysFBDriverLink1: TFDPhysFBDriverLink
    Left = 216
    Top = 40
  end
  object FDGUIxWaitCursor1: TFDGUIxWaitCursor
    Provider = 'Forms'
    Left = 368
    Top = 40
  end
  object qryScriptCategorias: TFDQuery
    Connection = ConexaoDB
    SQL.Strings = (
      'EXECUTE BLOCK AS'
      'BEGIN'
      '  IF (NOT EXISTS ('
      '    SELECT 1 '
      '    FROM RDB$RELATIONS '
      '    WHERE RDB$RELATION_NAME = '#39'VENDAS_ITENS'#39
      '  )) THEN'
      '  BEGIN'
      '    EXECUTE STATEMENT '#39
      '      CREATE TABLE VENDAS_ITENS ('
      '        VENDA_ID INTEGER NOT NULL,'
      '        PRODUTO_ID INTEGER NOT NULL,'
      '        "DATA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
      '        VALOR_UNITARIO DECIMAL(12,2) DEFAULT 0.00,'
      '        QUANTIDADE DECIMAL(12,2),'
      '        VALOR_TOTAL DECIMAL(12,2) DEFAULT 0.00'
      '      );'
      '    '#39';'
      '  END'
      'END;')
    Left = 760
    Top = 48
  end
  object qryScriptClientes: TFDQuery
    Connection = ConexaoDB
    SQL.Strings = (
      'EXECUTE BLOCK AS'
      'BEGIN'
      '  IF (NOT EXISTS ('
      '    SELECT 1 '
      '    FROM RDB$RELATIONS '
      '    WHERE RDB$RELATION_NAME = '#39'CLIENTES'#39
      '  )) THEN'
      '  BEGIN'
      '    EXECUTE STATEMENT '#39
      '      CREATE TABLE CLIENTES ('
      '        ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,'
      '        NOME VARCHAR(100),'
      '        ENDERECO VARCHAR(100),'
      '        CIDADE VARCHAR(100),'
      '        BAIRRO VARCHAR(100),'
      '        ESTADO VARCHAR(2),'
      '        CEP VARCHAR(20),'
      '        TELEFONE VARCHAR(20),'
      '        EMAIL VARCHAR(100),'
      '        DATANASCIMENTO DATE,'
      '        CONSTRAINT CLIENTES_PK PRIMARY KEY (ID)'
      '      );'
      '    '#39';'
      '  END'
      'END;')
    Left = 760
    Top = 120
  end
  object qryScriptProdutos: TFDQuery
    Connection = ConexaoDB
    SQL.Strings = (
      'EXECUTE BLOCK AS'
      'BEGIN'
      '  IF (NOT EXISTS ('
      '    SELECT 1 '
      '    FROM RDB$RELATIONS '
      '    WHERE RDB$RELATION_NAME = '#39'PRODUTOS'#39
      '  )) THEN'
      '  BEGIN'
      '    EXECUTE STATEMENT '#39
      '      CREATE TABLE PRODUTOS ('
      '        ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,'
      '        NOME VARCHAR(100),'
      '        DESCRICAO VARCHAR(200),'
      '        VALOR NUMERIC(15,2),'
      '        QUANTIDADE NUMERIC(15,2),'
      '        CATEGORIA_ID INTEGER,'
      '        CONSTRAINT INTEG_3 PRIMARY KEY (ID)'
      '      );'
      '    '#39';'
      '  END'
      'END;')
    Left = 760
    Top = 200
  end
  object qryScriptVendas: TFDQuery
    Connection = ConexaoDB
    SQL.Strings = (
      'EXECUTE BLOCK AS'
      'BEGIN'
      '  IF (NOT EXISTS ('
      '    SELECT 1 '
      '    FROM RDB$RELATIONS '
      '    WHERE RDB$RELATION_NAME = '#39'VENDAS'#39
      '  )) THEN'
      '  BEGIN'
      '    EXECUTE STATEMENT '#39
      '      CREATE TABLE VENDAS ('
      '        ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,'
      '        "DATA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
      '        CLIENTE_ID INTEGER,'
      '        VALOR_TOTAL DECIMAL(12,2) DEFAULT 0.00'
      '      );'
      '    '#39';'
      '  END'
      'END;')
    Left = 760
    Top = 280
  end
  object qryScriptVendasItens: TFDQuery
    Connection = ConexaoDB
    SQL.Strings = (
      'EXECUTE BLOCK AS'
      'BEGIN'
      '  IF (NOT EXISTS ('
      '    SELECT 1 '
      '    FROM RDB$RELATIONS '
      '    WHERE RDB$RELATION_NAME = '#39'VENDAS_ITENS'#39
      '  )) THEN'
      '  BEGIN'
      '    EXECUTE STATEMENT '#39
      '      CREATE TABLE VENDAS_ITENS ('
      '        VENDA_ID INTEGER NOT NULL,'
      '        PRODUTO_ID INTEGER NOT NULL,'
      '        "DATA" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,'
      '        VALOR_UNITARIO DECIMAL(12,2) DEFAULT 0.00,'
      '        QUANTIDADE DECIMAL(12,2),'
      '        VALOR_TOTAL DECIMAL(12,2) DEFAULT 0.00'
      '      );'
      '    '#39';'
      '  END'
      'END;')
    Left = 760
    Top = 352
  end
end
